### ISSUE TITLE
Not working, crap :(

### ISSUE THREAD

**Issue by TheKing1543** [Q-Ball/hudcreator#1]
I guess you are not interested in developing this again, but I simply can't get it to work, using PHP 8.1 and nginx.

![imagen](https://github.com/Q-Ball/hudcreator/assets/84400712/ed46b014-ba54-448a-90cc-14ec4d605513)
Even tho I put the steam api key and the return link it doesn't work.

also, whenever I click any of the buttons, they do not work either, just change resolution, reset and login to steam (doesn't work as I said)
![imagen](https://github.com/Q-Ball/hudcreator/assets/84400712/09b62501-895a-4ba0-9ebc-8f6972d024ad)

**Comment by TheKing1543** [comment]
Will post if I get it to work again or if you say smth

**Comment by Q-Ball** [comment]
Hello there! Sorry, but I do not plan to work on this project, so you will have to fork it and work on it yourself. Archiving this.
